security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_spring_boot_java?useTimezone=true&serverTimezone=UTC
      username: root
      password: 134336rj
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false 
springdoc:
  pathsToMatch: 
    - /auth/**
    - /person/**
    - /book/**
  swagger-ui:
    use-root-path: true
